name: Cart CI - Dev Branch
on:
  push:
  branches:
      - "!main"
jobs:
  common:
    uses: mukeshsahu20/github-actions-reusable/.github/workflows/ci.yaml@main
    with:
      component_name: cart


